import assert from 'node:assert/strict';
import { AgentAuth, RenderingVideo } from '../dist/index.js';
const baseUrl = process.env.RV_TEST_ORIGIN;
assert.ok(baseUrl?.startsWith('http://127.0.0.1:'));
const api = new RenderingVideo({ apiKey: 'sk-contract', baseUrl });
const config = { meta: { version: '2.0.0', width: 1280, height: 720, fps: 30, title: 'Schema title' }, assets: { svgs: [{ id: 'logo', svg: '<svg xmlns="http://www.w3.org/2000/svg"/>' }] }, tracks: [{ clips: [{ type: 'svg', svg: { $ref: 'logo' }, start: 0, duration: 2 }] }] };
assert.ok((await api.getCapabilities()).schema.clipTypes.includes('three'));
const task = await api.video.create({ config, title: 'SDK launch', category: 'marketing', metadata: { campaign: 'launch' } });
assert.equal(task.title, 'SDK launch');
assert.equal((await api.video.list({ category: 'all' })).tasks[0].category, 'marketing');
assert.equal((await api.preview.create(config)).tempId, 'preview-test');
assert.ok((await api.preview.get('preview-test')).config.meta);
await api.preview.convert('preview-test', { metadata: { campaign: 'launch' } });
await api.preview.render('preview-test', { metadata: { campaign: 'launch' }, numWorkers: 2 });
await api.video.render(task.taskId, { numWorkers: 2 });
assert.equal((await api.files.uploadBuffer(Buffer.from('test'), 'test.png', 'image/png')).count, 1);
const auth = new AgentAuth({ agentKey: 'ak_contract', device: AgentAuth.generateDevice(), baseUrl });
const client = new RenderingVideo({ auth });
await Promise.all([client.agent.context(), client.credits.get()]);
assert.equal((await client.agent.audit({ allKeys: true, riskLevel: 'high risk' })).total, 0);
await assert.rejects(client.agent.audit({ riskLevel: 'denied' }), e => e.code === 'INSUFFICIENT_SCOPE');
auth.invalidate();
await client.agent.context();
await client.files.uploadFile(new Blob(['test'], { type: 'image/png' }), 'test.png');
await assert.rejects(auth.headers('GET', new URL('https://different.example/api/v1/credits')), /outside/);
console.log('Node SDK contracts and device proof passed');
